### ISSUE TITLE
Cache does not save Content Headers

### ISSUE THREAD

**Issue by joe-elliott** [Cimpress-MCP/dotnet-core-httputils#13]
In HttpResponseMessageExtensions.cs the CopyCachable method only copies response.Headers onto the copy.  It also needs to copy response.Content.Headers.

In my application this is causing the Content-Type and Last-Modified Headers to be dropped.

**Comment by wparad** [comment]
@number101010, Thanks for catching this, can you add in those changes in PR, and I will get it merged.
