### ISSUE TITLE
Add Retry timeout for each attempt in RetryHandler

### ISSUE THREAD

**Issue by carlosflorencio** [Cimpress-MCP/dotnet-core-httputils#16]
Hi, thanks for this great lib!

The RetryHandler is not handling correctly timeouts: 
```C#
var handler = new RetryHandler(new MeasurementHandler(_logger), 3);
 _httpClient = new HttpClient(handler);
 _httpClient.Timeout = TimeSpan.FromSeconds(5);

// Shoud try 3 times but throws after first timeout
var response = await _httpClient.GetAsync("https://httpbin.org/delay/10");
```

Am i missing something? Thanks

**Comment by wparad** [comment]
@iamfreee, I'm trying to envision how this might work, but I am not sure I can come up with something.  The Timeout applies to the whole request, there is no way around that.  Possibly there could be an alternative timeout associated with each retry, but that functionality doesn't exist here.  I'm going to change the issue to reflect this request.

**Comment by thoean** [comment]
The `RetryHandler` is a `HttpMessageHandler`, that is, it's used by the `HttpClient`. There might be multiple message handlers (with each their own inner handler) associated. See https://github.com/Cimpress-MCP/dotnet-core-httputils/wiki (section "combining multiple message handlers") for details how to do that.

Translated for your case that means, if the HttpClient has an overall timeout of 5 seconds, that's the timeout for the complete call. So if you do retries, the combination of the retries needs to succeed in those 5 seconds.

Can you verify that? Can you for example set the timeout to 35 seconds and see whether above example suceeds?

**Comment by carlosflorencio** [comment]
@wparad is wright, the Timeout applies to the whole request. That's said, the only solution i am seeing is to apply a timeout foreach retry.

A solution can be to create a new extension method for the HttpClient itself and use the retry logic with the GetAsync(Uri, CancellationToken) method, and apply a timeout foreach token.

Another note, the RetryHandler always makes one more request: 
https://github.com/Cimpress-MCP/dotnet-core-httputils/blob/master/src/Cimpress.Extensions.Http/MessageHandlers/RetryHandler.cs#L48

I don't know, if this is intentional but when using `new RetryHandler(new MeasurementHandler(_logger), 3);` for example we only expect 3 tries but 4 requests are made.

Thanks!

**Comment by thoean** [comment]
@iamfreee, it's the number of retries, not number of tries. Does that make sense then?

**Comment by wparad** [comment]
@thoean I think the point is that is confusing for the users to understand what that field means.  You think oh `int` that means do it X times, I actually had the same thought before I looked at the source code.

**Comment by carlosflorencio** [comment]
@wparad yep!

It's a bit confusing the way it is now.

**Comment by wparad** [comment]
I'm going to opt for closing this issue and instead fixing the problem in #21.
